packages:
  - packages/*
  - play
  - docs

catalogs:
  prod:
    vue: ^3.4.0
    vite: ^5.4.0
    typescript: ^5.6.3
    '@vitejs/plugin-vue': ^5.0.4
    'vite-plugin-dts': ^3.8.3
    'element-plus': ^2.7.0
    vitepress: ^1.3.1


